export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  START_TRAINING: "/Start-traning",
  STATS: "/stats",
  USER: "/user",
  USER_EDIT: "/user/edit",
  CALENDAR: "/calendare",
  LIBRARY: "/library",
  CREATE_TRAINING: "/create-training",
  WORKOUT_PLAN: "/training/plan",
  WORKOUT_ACTIVE: "/training/active",
  WORKOUT_FINISH: "/training/finish",
  WORKOUT_HISTORY: "/training/history",
  START_TASTING: "/start-tasting",
  TASTING: "/tasting",
  TASTING_FINISH: "/tasting/finish",
};
