export const USER_STORAGE_METHODS = [
  "getById",
  "login",
  "register",
  "updateProfile",
  "updateTrainingResult",
  "saveTrainingPlan",
  "saveTrainingFeedback",
  "scheduleWorkout",
  "rescheduleWorkout",
  "cancelWorkout",
  "skipWorkout",
  "completeWorkout",
  "getWorkoutStats",
  "getGamificationCatalog",
];
